### ISSUE TITLE
Return to Menu throws nullref if host exits the game

### ISSUE THREAD

**Issue by gekidoslair** [Unity-Technologies/com.unity.multiplayer.samples.coop#147]
**Describe the bug**

If all players lose, you get prompted to return to the menu - clicking 'return' throws a null exception if the host has left:

NullReferenceException: Before using the library you should call Init() and do not forget to call Shutdown() afterwards
MLAPI.Transports.UNET.RelayTransport.Disconnect (System.Int32 hostId, System.Int32 connectionId, System.Byte& error) (at Library/PackageCache/com.unity.multiplayer.mlapi@54393f36bf/Runtime/Transports/UNET/RelayTransport.cs:213)
MLAPI.Transports.UNET.UnetTransport.DisconnectLocalClient () (at Library/PackageCache/com.unity.multiplayer.mlapi@54393f36bf/Runtime/Transports/UNET/UnetTransport.cs:296)
MLAPI.NetworkingManager.StopClient () (at Library/PackageCache/com.unity.multiplayer.mlapi@54393f36bf/Runtime/Core/NetworkingManager.cs:572)
BossRoom.Visual.PostGameUI.OnMainMenuClicked () (at Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs:85)
UnityEngine.Events.InvokableCall.Invoke () (at <42a5878ce129403083acccf18e43363f>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <42a5878ce129403083acccf18e43363f>:0)
UnityEngine.UI.Button.Press () (at C:/Program Files/Unity/Hub/Editor/2020.2.7f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2020.2.7f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2020.2.7f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/Program Files/Unity/Hub/Editor/2020.2.7f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:262)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/Unity/Hub/Editor/2020.2.7f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:385)

**To Reproduce**

Start a game with more than one player (host + client)
let all players die
you are prompted to replay again. 
quit the host application
hit 'replay' on the client

**Expected behavior**
to probably not do this.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2020.2f7
 - BossRoom Version: latest master branch (dc06548e7e040f0ca299688a19d1b3217611d1a5)

**Comment by SamuelBellomo** [comment]
Fixed, not happening anymore.
