### ISSUE TITLE
Changing some enums to scriptable objects

### ISSUE THREAD

**Issue by tuleky** [Unity-Technologies/com.unity.multiplayer.samples.coop#264]
**Feedback**
![image](https://user-images.githubusercontent.com/13554990/113936422-68c38c80-9800-11eb-92a7-55332e463a88.png)
![image](https://user-images.githubusercontent.com/13554990/113936436-6d884080-9800-11eb-9308-24f3f54103f6.png)

Situations where sample space is limited with few options is a good fit for old plain C# enums like the one below

![image](https://user-images.githubusercontent.com/13554990/113936913-2189cb80-9801-11eb-9e19-5c746cfb098b.png)

**Suggested Changes**
For situations like these ones, ScriptableObject enums are more robust, they give more flexibility, we can add logic to them and they can still work like a enum, we can add new enum without changing code (and we wouldn't be afraid to lose the number order when we add it to the first row, where in plain C# enums it would be horrible). There isn't any drawback that I know so it is safe to change it, there is just too much enum usages that makes work a little taxing, but I would love to do that!

**Comment by SamuelBellomo** [comment]
Hey @tuleky thank you for this!
Please go ahead!
The only advice we'd give you is create smaller PRs for your individual features against the develop branch. (for example one PR for character data)
This'll be great to continue the conversation, see what you have in mind.

**Comment by tuleky** [comment]
I couldn't find a way to change those enum to scriptable objects, I think the reason is I haven't known multiplayer architecture well, sending huge CharacterClass via networkvariable every tick is so inefficient, we definitely have to use enum in this scenario.

One suggestion would be I think we don't networkvariable for syncing character classes for late joiners, there could be a little system which sends character classes to the new comers via rpc calls rather than networkvariable. That way we could use CharacterClass for sending data over network.

**Comment by SamuelBellomo** [comment]
Hey Tuleky! A quick solution for this, you could generate an ID dynamically (in your SO's OnValidate if it's not generated yet). That would give a way to identify SOs and be able to exchange only that ID on the network. What do you think?

**Comment by SamuelBellomo** [comment]
I would highly suggest keeping NetVars for that kind of data instead of RPCs. (See this article here on why https://docs-multiplayer.unity3d.com/docs/learn/rpcvnetvar)

**Comment by tuleky** [comment]
> Hey Tuleky! A quick solution for this, you could generate an ID dynamically (in your SO's OnValidate if it's not generated yet). That would give a way to identify SOs and be able to exchange only that ID on the network. What do you think?

Hmm, that sounds nice. So we still need some kind of dictionary implementation for finding character class via using ID, what would we gain for doing that?

**Comment by SamuelBellomo** [comment]
The advantage is you wouldn't need an enum with a switch case. It could be populated dynamically. It would allow to add new classes or actions without code changes

**Comment by tuleky** [comment]
![image](https://user-images.githubusercontent.com/13554990/117891230-39041a80-b2bf-11eb-8e6d-665190369c92.png)

We also need a solution for imps, they need to be set up before launch.

**Comment by SamuelBellomo** [comment]
fixed
