### ISSUE TITLE
ServerCharacter Revive method HP parameter not used

### ISSUE THREAD

**Issue by AignerGames** [Unity-Technologies/com.unity.multiplayer.samples.coop#267]
The HP parameter seems to be ignored and the health is set to the base (max) value instead. 

https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/db507ac93b1323d70883dff571c49e8e3fc2eea2/Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs#L243

https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/db507ac93b1323d70883dff571c49e8e3fc2eea2/Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs#L247

**Comment by chrispope** [comment]
Fixed in v0.2.0
