### ISSUE TITLE
Gracefully handle "Trying to destroy object that doesn't exist".

### ISSUE THREAD

**Issue by JesusLuvsYooh** [Unity-Technologies/com.unity.multiplayer.samples.coop#276]
Play the game with 2 players, within 30 seconds, 97+ yellow warnings can fill the console.
Have a check for it to prevent log spam.
Might be worrying for new users to see all that appear + log spam can cause lag on low end hardware, especially if the logs are not turned off and game is released, or open for long periods.

![Screenshot 2021-04-13 at 11 06 06](https://user-images.githubusercontent.com/57072365/114535873-67eb8a00-9c48-11eb-9de6-bf33075d5d02.jpg)

**Comment by LukeStampfli** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi/issues/677 and MTT-556
are tracking this MLAPI bug.

**Comment by SamuelBellomo** [comment]
Looks like this is a duplicate MLAPI, it'd make sense to close it

**Comment by SamuelBellomo** [comment]
closing as duplicate, please follow the linked ticket above for updates
