### ISSUE TITLE
WebGL build error

### ISSUE THREAD

**Issue by pnkapadia64** [Unity-Technologies/com.unity.multiplayer.samples.coop#340]
On switching the platform to WebGL, I unchecked `Auto Graphics API` in player settings. 
After that the build gives some errors like:
1 - `'NetworkTransport' does not contain a definition for 'QueueMessageForSending'`
2 - `'NetworkTransport' does not contain a definition for 'SendQueuedMessages'`
3 -
```
UnityEditor.BuildPlayerWindow+BuildMethodException: 5 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002be] in /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:190 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:95 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

**Screenshots**
<img width="911" alt="Screenshot 2021-05-26 at 4 49 27 PM" src="https://user-images.githubusercontent.com/56364747/119651399-9ad98e00-be42-11eb-83b9-8eef2a990c4f.png">

<img width="1353" alt="Screenshot 2021-05-26 at 4 41 37 PM" src="https://user-images.githubusercontent.com/56364747/119650356-5d283580-be41-11eb-9c19-a8a928267641.png">

**Environment (please complete the following information):**
 - OS: MacOS 10.15.7
 - Unity Version: 2020.3.9f1
 - BossRoom Version: 0.2.0

**Comment by SamuelBellomo** [comment]
Hello @pnkapadia64 ! WebGL isn't currently supported by MLAPI nor Boss Room

**Comment by SamuelBellomo** [comment]
You can see the status here
https://resources.unity.com/unity-engine-roadmap/multiplayer#roadmap
Marking this as "in consideration", following the public roadmap's current status
