### ISSUE TITLE
CANT EVEN OPEN IT!

### ISSUE THREAD

**Issue by Coder547** [Unity-Technologies/com.unity.multiplayer.samples.coop#373]
**Describe the bug**

**To Reproduce**
1. Go to Unity Hub
2. Click on the folder inside the zip
3. Open the project.
4. SCREW IT!!!

**Expected behavior**
ACT AS A NORMAL PROJECT!!!
**Screenshots**
HOW THE HECK CAN I ADD ONE?

**Environment (please complete the following information):**
 - Windows 10
 - 2020.3.8f1
 - BossRoom Version: [e.g. v0.1.0] (I GOT IT FROM HERE YESTERDAY!)

**Comment by Coder547** [comment]
![2021-10-02](https://user-images.githubusercontent.com/91792279/135721701-3ed8eb15-acb7-480e-9e93-cc670e3bb2cc.png)
![2021-10-02 (1)](https://user-images.githubusercontent.com/91792279/135721718-6c7090d4-5a34-4f44-be11-fb2474bb71ac.png)

**Comment by Coder547** [comment]
SCREW IT!!!

**Comment by LukeStampfli** [comment]
I'm sorry for the inconnveniences you encountered. Boss Room requires that git is installed on your machine. You can install git here: https://git-scm.com/
After installing git, please restart your machine and try again.
