### ISSUE TITLE
Unable to reach host/server when connecting 2 or more clients with IP

### ISSUE THREAD

**Issue by ashwinimurt** [Unity-Technologies/com.unity.multiplayer.samples.coop#377]
**Describe the bug**

Unable to reach host/server when connecting 2 or more clients with IP. 
The issue only occurs when host is also a built player. Does not occur when host is on the Editor playmode.

**To Reproduce**
1. Build Boss Room. 
2. Open multiple instances of player.
3. Start the game as host and connect clients with IP. 
4. Fails on connecting the 2nd client. 

**Expected behavior**
Connecting upto 7 clients should work,

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2020.3.21f1
 - BossRoom Version: https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/tree/sam/feature%2Fupdating-to-latest-netcode @1f4262c74b12b85ee6f655ff59d7254cbb1b2e55

**Additional context**
None

**Comment by SamuelBellomo** [comment]
Have you tried using a dev build for this? We recognize this isn't a great flow and we want to look into a better flow for this.

**Comment by SamuelBellomo** [comment]
https://jira.unity3d.com/browse/MTT-1896

**Comment by SamuelBellomo** [comment]
With this upcoming boss room release, the -AuthProfile command line parameter can be used to start multiple instances of the same build locally.
