### ISSUE TITLE
Can't add a new character

### ISSUE THREAD

**Issue by slee4431** [Unity-Technologies/com.unity.multiplayer.samples.coop#392]
Hi guys. I'm really new to programming, so please go easy on me. I've been trying to add my own character to Boss Room for the past week, but I can't get past this without throwing the System.Exception. It's from GameDataSource.cs.

public Dictionary<CharacterTypeEnum, CharacterClass> CharacterDataByType
        {
            get 
            {
                if( m_CharacterDataMap == null )
                {
                    m_CharacterDataMap = new Dictionary<CharacterTypeEnum, CharacterClass>();
                    foreach (CharacterClass data in m_CharacterData)                  
                    {
                        if (m_CharacterDataMap.ContainsKey(data.CharacterType))
                        {
                            throw new System.Exception($"Duplicate character definition detected: {data.CharacterType}");
                        }                     
                        m_CharacterDataMap[data.CharacterType] = data;
                    }
                }           
                return m_CharacterDataMap;              
            }
        }
}

These are the steps I'm taking to create a new character. Well, the latest way. I've tried like 3 different ways, but I only documented what I did the last time. The System.Exception gets thrown immediately after I click on a character in the Character Select scene. I just don't understand why my new character PlayCharacter is considered a duplicate, but the other 6 CharacterClass.CharacterType not?

Any help would be very much appreciated. Thank you.

Steps I took to add a new character (just did it with a simple cube, prefab called CharacterPlayer):
1. Create CharacterPlayer prefab and add to Prefabs-CharGFX folder 
2. Add CharacterPlayer Prefab to PlayerGraphics prefab in Prefabs-CharGFX
2. Add new type to CharacterTypeEnum.cs, calling it CharacterPlayer
6. Add new ActionType called LavaCube to public enum ActionType in ActionRequestData.cs
7. Create the following Scriptable Objects, all called CharacterPlayer:
a) Character Class SO 
b) BaseHP SO
c) Action Description(s) SO
8. Update the GameDataSource Prefab by adding Character Class SO and Action Description SO
9. Increase k_MaxLobbyPlayers in CharSelectData.cs
10. Add new "LobbySeatConfiguration(CharacterTypeEnum.CharacterPlayer,8" to ChatSelectData.cs
11. Duplicate an existing seat, edit as necessary and then drag and drop new PlayerSeat GO into Player Seats in CharSelectState in editor.

Then I hit Play, get to the Character Select scene, but then get hit with the System.Exception as soon as I choose any character.

Thanks guys!

**Comment by fernando-cortez** [comment]
Hello.

Here's the quickest way to add a new character to the game:

- Under GameData/Avatars, create a new Avatar ScriptableObject (SO).
- Under GameData/Characters, create a new Folder for your new Character. Inside that, create a CharacterClass SO, as well as a IntVariable SO to represent its health.
- Inside the CharacterTypeEnum.cs file, add a new enum for your new character.
- Inside Prefabs/CharGFX/CharacterGraphics, create your visual, in-game character representation. A cube here would suffice.
- Inside Prefabs/CharGFX/CharacterGraphics/CharacterSelect, create a variant of the previous prefab, or a new one entirely, and make sure this new prefab has an Animator attached.
- Now go back to the Avatar that you created in the first step. Attach the appropriate SOs to the fields available. For the Portrait field, just add any image from the project.
- Under GameData/Systems, add your populated Avatar to the array of Avatars inside of the AvatarRegistry SO.
- Add new Avatar SO to Prefabs/GameDataSource's GameDataSource.CharacterData array.
- Open Prefabs/State/CharSelectState and add Avatar SO to CharSelectData's ChatSelectData.AvatarConfiguration array.
- Open Prefabs/UI/CharSelectStateCanvas, and add a new PlayerSeat prefab to PlayerSeats (just duplicating the male Rogue class will do). Offset it, and add any Sprites to distinguish it as new. Add the Avatar enum to UICharSelectPlayerSeat component on the new seat.
- Inside CharSelect scene, add the new player seat to CharacterSelectState's PlayerSeats array.

At this point you should be able to visualize your new character in the character select screen, as well as in-game. Give your character a speed value greater than 0 (inside of the CharacterClass SO) to see it move around.

Let us know if you're still seeing any issues adding a new Character!

**Comment by slee4431** [comment]
Hi Fernando, I can't tell you how grateful I am for such a comprehensive response :)
I am still getting the following pesky error message, but it is no longer game-breaking:

Exception: Duplicate character definition detected: Tank
Unity.Multiplayer.Samples.BossRoom.GameDataSource.get_CharacterDataByType () (at Assets/BossRoom/Scripts/Shared/Data/GameDataSource.cs:43)
Unity.Multiplayer.Samples.BossRoom.Server.AIBrain.get_CharacterData () (at Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs:153)
Unity.Multiplayer.Samples.BossRoom.Server.AIBrain.get_DetectRange () (at Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs:166)
Unity.Multiplayer.Samples.BossRoom.Server.IdleAIState.DetectFoes () (at Assets/BossRoom/Scripts/Server/Game/AIState/IdleAIState.cs:31)
Unity.Multiplayer.Samples.BossRoom.Server.IdleAIState.Update () (at Assets/BossRoom/Scripts/Server/Game/AIState/IdleAIState.cs:26)
Unity.Multiplayer.Samples.BossRoom.Server.AIBrain.Update () (at Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs:60)
Unity.Multiplayer.Samples.BossRoom.Server.ServerCharacter.Update () (at Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs:261)

Thank you again. I am finding the coding community so altruistic. Hope to eventually become a part of it.
