### ISSUE TITLE
Error reading movie files in untiy (linux mint)

### ISSUE THREAD

**Issue by BrahRah** [Unity-Technologies/com.unity.multiplayer.samples.coop#421]
**Describe the bug**
I've loaded the project and am presented with following errors:

![errors](https://user-images.githubusercontent.com/40721994/143867556-39b9dfb8-cf9b-4da6-bed2-8b0c4d496d0d.png)

**Environment (please complete the following information):**
 - OS: [e.g. Linux Mint 20.1]
 - Unity Version: [2020.3.23f1.1294]
 - BossRoom Version: [e.g. v1.0.1pre]

**Comment by LPLafontaineB** [comment]
Thank you for reporting this issue. I submitted a PR updating the package causing this. The newer version has those files in a format that is compatible with Linux.
