### ISSUE TITLE
CPU overhead due to Dispatcher.Dispatch()

### ISSUE THREAD

**Issue by leonidasos** [Unity-Technologies/com.unity.multiplayer.samples.coop#466]
**Description**
I've tried Boss Demo. I've got huge cpu overhead caused by *DispathFrame() in NetworkMetrics that causes much lower fps. At first stage I did not run profiler. I run it later to search for clues what's causing the problem.

**To Reproduce**
1. Run game and watch statistics.  Just stay at same place at the beginning of level
2. Stop game
3. Comment out Dispatcher.Dispatch() in NetworkMetrics 
```
public void DispatchFrame()
{
    //Dispatcher.Dispatch();
    m_NumberOfMetricsThisFrame = 0;
}
```
4. Run a game and compare statistics (be sure that Dispatch() is commented out)

**Screenshots**
[https://cdn.discordapp.com/attachments/819614776165793852/936625306062704640/2022-01-27_16h34_53.png](url)

**Environment (please complete the following information):**
 - Windows 10
 - Unity Version: 2021.2.8f1
 - BossRoom Version:  tag: v1.0.1-pre,
 
**Additional context**
![stats](https://user-images.githubusercontent.com/2396651/152622549-e336b1b2-616a-4d84-b189-9540f1c64011.png)

**Comment by ashwinimurt** [comment]
Hi @leonidasos Thanks for reporting this issue.
I have created https://jira.unity3d.com/browse/MTT-2627 internally for us to track and triage this. 
For future issues related to `Netcode for Gameobjects`, please report them using the Unity Bug Reporter. Thank you :)

**Comment by ashwinimurt** [comment]
Removed Awaiting traige label

**Comment by LukeStampfli** [comment]
Since this is an issue with the tools package and not Boss Room I'm gonna close this here. We've tracked this internally as Ashwini already mentioned.
