### ISSUE TITLE
Unable to start as host after trying to connect as client to ip that isn't hosting

### ISSUE THREAD

**Issue by JeffWTD** [Unity-Technologies/com.unity.multiplayer.samples.coop#493]
**Describe the bug**

Unable to start as host after trying to connect as client to ip that isn't hosting.
Occurs in editor and in build

**To Reproduce**

1. Open Boss Room in Editor or Build
2. Click "Join"
3. Close trying to join dialog
4. Click "Start"
5. Notice that it will never start as host

**Environment** (please complete the following information):

OS: Windows 10
Unity Version: 2020.3.28f1
BossRoom Version: 1.0.2 pre

**Comment by SamuelBellomo** [comment]
@pdeschain can you validate there is no way to get this type of behaviour with your lobby work please?

**Comment by JeffWTD** [comment]
Can you elaborate what you mean by "with your lobby work"? Not sure what you want me to do. =)

**Comment by SamuelBellomo** [comment]
Lobby work done in latest releases
https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/releases/tag/v1.1.2-pre

**Comment by SamuelBellomo** [comment]
@fernando-cortez to link your fix

**Comment by SamuelBellomo** [comment]
@JeffWTD This was most likely an NGO issue that has since been fixed. I'll close this issue for now, let us know if you still see this.
