### ISSUE TITLE
Authentication Failed: Invalid_parameters valid ID domain not specified 

### ISSUE THREAD

**Issue by NerdyChara** [Unity-Technologies/com.unity.multiplayer.samples.coop#609]
**Describe the bug**
When I open up the menu; it sends two error messages. One a warning and the other with an formal error. 
The message is near identical. "[Authentication]: Request failed: 400, {"title":"INVALID_PARAMETERS","detail":"Valid ID Domain not specified","details":[],"status":400}"

**To Reproduce**
1. Download the latest version, which as of now is v1.1.0-pre.
2. Add the project and open it with Unity Personal 2020.3.33f1 
3. Open up the Startup Scene and hit play 

**Expected behavior**
I expected the main menu to show up and stay open. 

**Screenshots**
![Screenshot of console](https://i.imgur.com/9JSyhaN.png) 

**Environment (please complete the following information):**
 - OS: Windows 10 
 - Unity Version: 2020.3.33f1
 - BossRoom Version: v1.10-pre

**Comment by NerdyChara** [comment]
I just found out it was because I forgot to setup the authentication services on the services section of the project settings.

**Comment by fernando-cortez** [comment]
@NerdyChara Funny enough, we have an open [PR](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/607) with better details when you run into this exact scenario. Thanks for the submission.
