### ISSUE TITLE
Boss Room v1.2.0 reconnection See the dead imp

### ISSUE THREAD

**Issue by haoshangce** [Unity-Technologies/com.unity.multiplayer.samples.coop#682]
![image](https://user-images.githubusercontent.com/31094149/174027437-4f14d230-86b4-47cb-a198-995ffecbb389.png)
![image](https://user-images.githubusercontent.com/31094149/174027453-cfe7567d-677b-4f30-a9cd-6d8f2ff52324.png)

**Comment by SamuelBellomo** [comment]
hey @haoshangce ! thanks for letting us know!
It's funny you're sending this now, we've been discussing solutions for this bug this week. It's been there for a while and we have come to a solution we'll be implementing in the next few weeks.
@fernando-cortez for more details.

**Comment by SamuelBellomo** [comment]
for internal tracking [MTT-1558](https://jira.unity3d.com/browse/MTT-1558)

**Comment by haoshangce** [comment]
I like BossRoom. Thank you

**Comment by fernando-cortez** [comment]
Resolution PR: https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/698.
