### ISSUE TITLE
Spawning an object with ownership leads to a different initial rotation between server and client

### ISSUE THREAD

**Issue by rCarleon** [Unity-Technologies/com.unity.multiplayer.samples.coop#694]
**Description**
I am using ClientNetworkTransform component on a gameobject. When spawning the object with a specific rotation (Z Axis) and with ownership (SpawnWithOwnerShip) the object is spawned on the client correctly with the correct rotation. On the server it is also spawned correctly at first, but it changes the rotation within a short period of time (1 second or so) to EulerAngles 0/0/0, resulting in a different Rotation between Server and Client.

When spawning the object first (without Ownership) and changing the ownership directly afterwards, the described behavior does not occur but the ownership of the gameobject is not applied (client can't transform object). Seems to be related to an already reported issue. 

Only tested with Z axis rotation. 

**To Reproduce**
1. Add NetworkObject and ClientNetworkTransform to an object which is going to be spawn
2. Create Clone of the Project and start the project as server and start the clone project as client
3. After the client has connected, instantiate the object with rotation 180 and spawn the object with ownership
4. Or use minimum  unity Project attached below

![Screenshot 2022-01-03 133126](https://user-images.githubusercontent.com/35304814/147930842-8c698521-1da4-4042-acdf-3570d3f81b84.jpg)

![Screenshot 2022-01-03 132914](https://user-images.githubusercontent.com/35304814/147930867-84d10161-9f05-4163-ac13-a540805cb957.jpg)

**Environment**
 - OS: [e.g. Windows 10]
 - Unity Version: [e.g. 2020.3.13]
 - Netcode Version: [e.g. 1.0.0-pre.3]
 - Netcode Commit: [e.g. https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi/commit/c102935df1d7e0928283b48948fe96e5d96dd961]

**Additional context**

[testing.zip](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/files/7801964/testing.zip)

**Comment by NoelStephensUnity** [comment]
This project, with a few minor updates since the v1.0.0-pre.3 release, works using the [PR-2102](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/pull/2102) branch.

**Comment by NoelStephensUnity** [comment]
This bug was resolved in v1.0.2.
I am including the adjusted testing.zip project that uses v1.0.2 that I used to confirm this is fixed.
[694_Resolved.zip](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/files/9686139/694_Resolved.zip)
