### ISSUE TITLE
ClientGameNetPortal 117 m_ConnectStatusPub.Publish(DisconnectReason.Reason);

### ISSUE THREAD

**Issue by haoshangce** [Unity-Technologies/com.unity.multiplayer.samples.coop#700]
Message not sent

**Comment by SamuelBellomo** [comment]
Hey @haoshangce 
Do you have more details on how this happened and steps to reproduce? The issue template should give you the things we need to help to better understand your issue.
We've also refactored our ConnectionManagement in our develop branch, is your issue still there on this branch for you?
