### ISSUE TITLE
Auto Change Host When Host Disconnected

### ISSUE THREAD

**Issue by DeveloperARKids** [Unity-Technologies/com.unity.multiplayer.samples.coop#706]
When I try the demo, the client is disconnected from lobby/game when the host left the game. Which I think this is old mechanism for multiplayer.
Can the host change automatically when the Host is leave from game?

**Comment by SamuelBellomo** [comment]
Hey @DeveloperARKids host migration isn't in scope for boss room at the moment, you can look at https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/issues/624 it has a bit more details on how we envision you could do this

**Comment by SamuelBellomo** [comment]
@DeveloperARKids updated the issue with corrected info
