### ISSUE TITLE
Npcs Attack Npcs

### ISSUE THREAD

**Issue by Fedi15** [Unity-Technologies/com.unity.multiplayer.samples.coop#727]
Hello to all Boss Room Devs, i am in the point where i want to make npc summoned by player to  attack npc from scene what is the best way to do it and thanks

**Comment by SamuelBellomo** [comment]
Hey @Fedi15 thanks for reaching out.
What part of the project have you looked at so far? Looking at your gameplay, looks like you could reuse most of our systems. Are there gameplay elements you're missing?
