### ISSUE TITLE
How is PLayerServerCharacter script is working

### ISSUE THREAD

**Issue by Fedi15** [Unity-Technologies/com.unity.multiplayer.samples.coop#730]
Hello , i want some help to understand playerServerCharacter script how the list is full of the all player in scene all i see it's on network spawn addiing current player to that list isn't should the list have only one player how the imp  can detect all player from it because i wanna use the  same way to make npc detect npc summonde from player and thanks

**Comment by Fedi15** [comment]
Okay let's say i wanna use same methode for the imps not player should i make if change instead of if server to client when adding new imp because i tried if server but it didn't work

**Comment by SamuelBellomo** [comment]
Not sure I follow.
To spawn a network object, just instantiate + spawn it.
To keep track of them, you can use a static list and register them to it in their respective OnNetworkSpawn.
