### ISSUE TITLE
ConnectionManager.cs doesnt compile

### ISSUE THREAD

**Issue by DancingAppsDays** [Unity-Technologies/com.unity.multiplayer.samples.coop#767]
Just installed de package and got this error, figure I might as well share it here:
Unity version used 20.3.38f1

Assets\Scripts\ConnectionManagement\ConnectionManager.cs(90,48): error CS8124: Tuple must contain at least two elements.

I noticed this in line 7:
using UUnity.BossRoom.ConnectionManagement;

I also had trouble with the ai.navigation, the URP and the Parrelsync package,
which i ended installing manually, but this seems unrelated... thanks in advance for any feedback

**Comment by DancingAppsDays** [comment]
Ok i solved by specifyng type of list in this line..
 List<ConnectionState> states =new List<ConnectionState>() { ...

Seems a problem using C#8 instead of C#9, maybe i do need Unity 2021 after all?
Since using UnityEngine.Pool is also missing

**Comment by chrispope** [comment]
Hi @DancingAppsDays, yes, please refer to the ReadMe on the repo where we call out compatibility:

> PLEASE NOTE: Boss Room is compatible with the latest Unity Long Term Support (LTS) editor version, currently [2021 LTS](https://unity.com/releases/2021-lts). Please include standalone support for Windows/Mac in your installation.

Thanks!
