### ISSUE TITLE
Link on Docs Broken

### ISSUE THREAD

**Issue by andresmonc** [Unity-Technologies/com.unity.multiplayer.samples.coop#787]
Seeing the link to this repo looks wonky. I'm running Chrome on Mac.
https://docs-multiplayer.unity3d.com/netcode/current/components/networktransform/index.html
<img width="995" alt="image" src="https://user-images.githubusercontent.com/41450290/203836394-a80ee90d-7823-463c-9705-a4008a57c7cb.png">

**Comment by TobGab97** [comment]
In my case worked adding "com.unity.multiplayer.samples.coop": "https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop.git?path=/Packages/com.unity.multiplayer.samples.coop#main" in Packages/manifest.json file at the root of my project

**Comment by andresmonc** [comment]
yeah looks like it's been resolved now
