### ISSUE TITLE
Mobile Joystick

### ISSUE THREAD

**Issue by Fedi15** [Unity-Technologies/com.unity.multiplayer.samples.coop#802]
Hello there, i wanna use mobile joystick for movment UI joystick i added in script client input sender in update this if statment 

               if m_Joystick.JoystickAxis != Vector2.zero)

                {
                    float h = m_Joystick.JoystickAxis.x;
                    float v = m_Joystick.JoystickAxis.y;
                    Vector3 movment = new Vector3(h,0,v);
                    movment = transform.position + movment;
                    m_ServerCharacter.SendCharacterInputServerRpc(movment);
                    //Send our client only click request
                    ClientMoveEvent?.Invoke(movment);
                }
but i think doing server rpg of the new poistion and invoke ClientMoveEvent in update is kinda heavy so what should i do

**Comment by SamuelBellomo** [comment]
Boss Room's networking is better for point and click events, League of Legends style, more than reactive joysticks and wasd + mouse.
For reactive movements, I'd suggest using the model we have our ClientDriven bitesize. You can find it here https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/tree/main/Basic/ClientDriven
Sending transform positions continuously for example should be done using ClientNetworkTransform.
Check out this doc too on how to deal with lag and authority https://docs-multiplayer.unity3d.com/netcode/current/learn/dealing-with-latency

**Comment by SamuelBellomo** [comment]
I'll close the issue, but don't hesitate to respond and reopen it if you have more questions.
