### ISSUE TITLE
CinemachinePipeline class is Deprecated

### ISSUE THREAD

**Issue by crawfis** [Unity-Technologies/com.unity.multiplayer.samples.coop#807]
**Describe the bug**
This sample seems to use an outdated Cinemachine, which leads to runtime errors and the camera not moving.

**To Reproduce**
1. Download latest Release Project.zip
2. Enable Relay and Lobby for the Project
3. Open With Unity 2022.2.1f
4. Update packages to Cinemachine to 2.9.5
5. Remove old Navmesh github package from the Manifest

**Expected behavior**
To be close to working with a newer version of Unity.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 11
 - Unity Version: 2022.2.1f
 - BossRoom Version: 2.0.4

**Additional context**
I know I shouldn't have opened it with a non LTS. Some things are fairly out of date though.

**Comment by SamuelBellomo** [comment]
Hey @crawfis Boss Room supports latest available LTS at the moment which is 2021LTS. We'll bump Boss Room to 2022LTS as soon as it releases, so for now, 2021 is the latest we'll support.

**Comment by LPLafontaineB** [comment]
Hi @crawfis , we are preparing to update Boss Room to 2022 for when the LTS releases, but I cannot reproduce this issue. I have my project updated to 2022.2.13f1, with Cinemachine version 2.9.5, but I don't see any runtime errors and the camera still moves as usual. What were the errors you saw?

**Comment by LPLafontaineB** [comment]
Closing this since we haven't been able to reproduce this issue after upgrading
