### ISSUE TITLE
New mode pvp

### ISSUE THREAD

**Issue by Fedi15** [Unity-Technologies/com.unity.multiplayer.samples.coop#811]
Hey, i want to make the game system work with player vs monster and player vs player two for now i tried make new variable boolean called isplayer with isNpc and changed some fonction of utility to make it that i can hit player two but i think i may didn't know to do it exacutly can you tell me the general idea of how i can do like some mode that player  can fight player and player can summon monster to fight the enemy and not targting me or player in my team.
1- i want to know best solution of how to make npc target other npc only if he is summoned from player if not  from player just targeting all player.
2- i want to know best solution of how to make player hit other player but from other team not my team.
genrally the idea of how i want to turn the game into is to two team playing vs eache other and why i want to make monster target only the enemy of his owner is because i did new skill that can summone monster helping until he die

**Comment by SamuelBellomo** [comment]
Hey @Fedi15 I'm afraid Boss Room was built as a coop game first. You'd need to dig through its code base and figure how to do it. There's quite a few behaviours for AIs that were hardcoded (like targeting players).
In general, NGO is supporting coop first. We're exploring and discussing pvp of course, but it's not officially supported yet.
