### ISSUE TITLE
Sharing Variable between scenes

### ISSUE THREAD

**Issue by Fedi15** [Unity-Technologies/com.unity.multiplayer.samples.coop#812]
i want add option of  team in  boss room charselect how can i get the team varaible from char select to boss room SCENE

**Comment by SamuelBellomo** [comment]
you could store this in a DontDestroyOnLoad object.
I see you're requesting support through a few issues like this, I suggest you join our Discord here https://discord.gg/buMxnnPvTb and the community will be able to help you. For questions that aren't multiplayer specific, the general unity Discord https://discord.gg/unity will be able to help
