### ISSUE TITLE
Broken code of conduct link

### ISSUE THREAD

**Issue by alexelwood14** [Unity-Technologies/com.unity.multiplayer.samples.coop#814]
**Describe the bug**
The link your Netcode code of conduct is broken

**To Reproduce**
1. Go to https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/CODE_OF_CONDUCT.md
2. Click on 'Netcode code of conduct'
3. Link goes to GitHub 404 page.

**Comment by SamuelBellomo** [comment]
Thank you, should be fixed on main now
