### ISSUE TITLE
Skinned Mesh Rendere is invisible in build

### ISSUE THREAD

**Issue by Fedi15** [Unity-Technologies/com.unity.multiplayer.samples.coop#819]
void AttachToMesh(SkinnedMeshRenderer mesh, int slotIndex) {

		if(!IsServer) return;
		if (currentMeshes [slotIndex] != null) {
			currentMeshes [slotIndex].gameObject.GetComponent<NetworkObject>().Despawn();
		}
		SkinnedMeshRenderer newMesh = Instantiate(mesh.equipment3D) as SkinnedMeshRenderer;
		newMesh.bones = targetMesh.bones;
		newMesh.rootBone = targetMesh.rootBone;
		currentMeshes [slotIndex] = newMesh;
		newMesh.gameObject.GetComponent<NetworkObject>().Spawn();
	}
when i spawn mesk.equipment3D it's not visible on game build but when i change instead of spawn mesk.equipment3D i make copy of player skinned mesh renderer and then i change it's property like shared mesh and shared material to the one mesk.equipment3D it work and visible in editor and build

**Comment by SamuelBellomo** [comment]
Unless I'm mistaken, this is more of an ask for support than a problem in boss room.
If it's a problem in boss room, please follow the issue template (the one showing when creating a new issue).
If it's an ask for support, please check out the #support channels in either multiplayer or main unity discord servers.
Closing this, please feel free to reopen with the proper issue template if this is a problem in boss room.
