### ISSUE TITLE
links from the docs page are broken

### ISSUE THREAD

**Issue by gekidoslair** [Unity-Technologies/com.unity.multiplayer.samples.coop#856]
**Describe the bug**

The links to the relay documentation on this page under the 'Relay Setup' section are broken (they have an extra '/relay/' at the end

https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop#exploring-the-project-1

**Comment by fernando-cortez** [comment]
Thanks for spotting this @gekidoslair.

The changes to the doc links should now be reflected on `main`.

Thanks!
