### ISSUE TITLE
Breaking: Headless servers reject clients

### ISSUE THREAD

**Issue by dylanh724** [Unity-Technologies/com.unity.multiplayer.samples.coop#859]
**Describe the bug**
When running a local headless Linux || Windows server (UDP), clients are auto-rejected.

**To Reproduce**

## Server

Leaving default scene build order:

1. Set NetworkManager `!ConnectionApproval`
2. Set NetworkManager LogLevel to `developer`
3. Set NetworkManager Address:Port to `127.0.0.1:7777`
4. Add `#if UNITY_SERVER` (or a cli `-arg` handler) to trigger `NetworkManager.Singleton.StartServer();`
5. Build a headless Windows || Linux server
6. Launch via CLI with `-batchmode -nographics`
7. Confirm local server is running via logs, eg: `127.0.0.1:7777`.

### (A)
1. Play in Editor
2. [UI] Join with direct IP: `127.0.0.1:7777` (should match server^)
3. [Logs] StartClient -> Intialize -> `Failed to connect to server`

### (B)
1. Play in Editor
2. [NetworkManager] Start Client
3. [Logs] StartClient -> Intialize -> `Failed to connect to server`

**Expected behavior**
Client should connect to headless server running `NetworkManager.Singleton.StartServer()` on init

**Screenshots**
![image](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/assets/8840024/da1ffa5d-91b8-4599-9a58-4045e27efe05)

![image](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/assets/8840024/b22b5904-cf6b-4301-9b9f-d970e37a23d1)

![image](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/assets/8840024/49355aa4-8223-4f1c-b57d-0ad6f131d57f)

![image](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/assets/8840024/c7435f6e-0397-49eb-b7b7-3f61e88d8a66)

**Environment (please complete the following information):**
 - OS: Win11
 - Unity Version: 2022.3.5 LTS
 - BossRoom Version: Latest from 08/15/2023 clone

**Additional context**

Connection **does** work if solely using UI, leading me to believe the issue has something to do with NetworkManager handling with `Startup`. I'll continue to look into this. Perhaps if server start with MainMenu instead of Startup, it may work.

**Comment by dylanh724** [comment]
## Issue Identified

If I build the headless server and leave off the `Startup` scene, the Clients can connect to the headless Server from the Menu. **However, **only** from logs.**

![image](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/assets/8840024/66c1e908-1db0-4ee7-8694-411207ff82c3)

The logs show a client<>server handshake and persists without disconnection. The server logs show confirmation of this:

```csharp
[Netcode] StartServer
[Netcode] A ConnectionApproval callback is defined but ConnectionApproval is disabled. In order to use ConnectionApproval it has to be explicitly enabled
[Netcode] Initialize
[Netcode] Client Connected
No client player ID found mapped to the given client ID: 1
[Netcode] [Server-Side Client-Synchronization] NetworkObject serialization order:UIMessageManagerSceneLoaderPersistentPlayer1
```

## Continued Issues

So we have a client<>server handshake, but UI does not respond as expected. To fix:

1. Startup scene needs to handle headless server auto-startup. Currently, starting a server and moving to the Menu scene seems to destroy the server (without logs or indicators). Building **without** Startup scene is the only way I could get this to connect.
2. When the Client connects to a headless server, the UI does not respond as expected: Nothing happens. 

I have a feeling that the UI desync has to do with the log `[Netcode] A ConnectionApproval callback is defined but ConnectionApproval is disabled. In order to use ConnectionApproval it has to be explicitly enabled`. 

Approval was enabled by default and the only way a headless server seems to be able to get this working is to disable this. 

## Lacking Documentation

As a true use of a client/server will often be likely to have a **headless** (dedicated) server rather than connecting as a "Host" via the UI, **there needs to be steps/testing/documentation for how to make this happen.** Any possibility we can get some of this rolling?

**Comment by LPLafontaineB** [comment]
Closing this issue as it has been a few weeks. If you require additional support feel free to reach out to us, or to the NGO team in [their repo](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects) or via our [discord server](https://discord.gg/FM8SE9E).
