### ISSUE TITLE
feat: WebGL+WSS support

### ISSUE THREAD

**Issue by dylanh724** [Unity-Technologies/com.unity.multiplayer.samples.coop#861]
After finding [this post](https://forum.unity.com/threads/how-to-use-ngo-with-webgl.1444894/), it seems that this demo !supports WebGL natively. Before this, one may attempt trial+error; let's save them time.

Can you folks add support for the latest version and add some documentation on WebGL+WSS?

If not, at minimum, can we update the docs to let users know the deal?

**Comment by LPLafontaineB** [comment]
Hi Dylan! Thank you again for this feedback and sorry for the delayed response.

Boss Room indeed does not support WebGL. The [docs](https://docs-multiplayer.unity3d.com/netcode/current/learn/bossroom/bossroom/index.html) and [Readme](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/README.md) list the platforms supported by this sample: Windows, MacOS, iOS, and Android.

However, while it has not been implemented in this specific sample, WebGL is still supported by Netcode for GameObjects. It would be possible to implement it into this sample, but it is not planned in our current roadmap.

If you require specific support into using WebGL in your projects, feel free to reach out to us, or to the NGO team in [their repo](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects) or via our [discord server](https://discord.gg/FM8SE9E) or the [multiplayer forum](https://forum.unity.com/forums/multiplayer.26/).
